version: "3.6"

services:
    app:
        build: .
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8008
        volumes:
            - .:/code
        ports:
            - "8008:8008"